#!/usr/bin/env python3
"""
Auto-generate Monty external function wrapper for a skill
Usage: python generate_monty_wrapper.py <skill-name> [options]
"""

import sys
import os
from pathlib import Path


def detect_tool_type(skill_name: str) -> str:
    """Detect if skill is subprocess or MCP type."""
    skill_path = Path(f".agent/skills/{skill_name}")

    if not skill_path.exists():
        return "unknown"

    tool_dir = skill_path / "tool"

    if not tool_dir.exists():
        return "unknown"

    # Check for MCP server
    if (tool_dir / "mcp_server.py").exists():
        return "mcp"

    # Check for main.py
    if (tool_dir / "main.py").exists():
        return "subprocess"

    return "unknown"


def generate_subprocess_wrapper(skill_name: str) -> str:
    """Generate wrapper for subprocess-based tools."""
    skill_snake = skill_name.replace("-", "_")
    base_name_display = skill_name.replace("-expert", "").replace("_", "-")
    base_name_func = skill_name.replace("-expert", "").replace("-", "_")

    template_lines = [
        f"# === {skill_name.title()} Functions ===",
        "# Auto-generated by generate_monty_wrapper.py",
        "",
        f'@register_external_function("{base_name_display}_main")',
        f"def {base_name_func}_main(**kwargs) -> dict:",
        '    """',
        f"    Main function for {skill_name} tool.",
        "",
        "    This function provides access to all "
        + skill_name
        + " functionality through Monty.",
        "",
        "    Args:",
        f"        **kwargs: Tool-specific arguments. See {skill_name}/tool/main.py CLI.",
        "",
        "    Returns:",
        "        Execution result as dict with keys depending on the operation.",
        "        May include 'output', 'error', or structured data.",
        '    """',
        "    from pathlib import Path",
        "    import subprocess",
        "    import sys",
        "    import json",
        "",
        f'    tool_dir = Path(__file__).parent.parent.parent / "{skill_name}" / "tool"',
        '    main_py = tool_dir / "main.py"',
        "",
        "    if not main_py.exists():",
        f'        return {{"error": f"Tool not found at {{main_py}}", "skill": "{skill_name}"}}',
        "",
        "    # Build command - pass all kwargs as CLI arguments",
        "    cmd = [sys.executable, str(main_py)]",
        "",
        "    # Convert kwargs to CLI arguments",
        "    for key, value in kwargs.items():",
        "        if isinstance(value, bool):",
        "            if value:",
        '                arg_name = key.replace("_", "-")',
        '                cmd.append(f"--{arg_name}")',
        "        elif value is not None:",
        '            arg_name = key.replace("_", "-")',
        '            cmd.extend([f"--{arg_name}", str(value)])',
        "",
        "    # Set appropriate timeout based on tool type",
        "    timeout = 60",
        f'    if "download" in "{base_name_display.lower()}":',
        "        timeout = 300",
        f'    elif "video" in "{base_name_display.lower()}":',
        "        timeout = 600",
        f'    elif "convert" in "{base_name_display.lower()}":',
        "        timeout = 120",
        "",
        "    try:",
        "        result = subprocess.run(",
        "            cmd,",
        "            capture_output=True,",
        "            text=True,",
        "            timeout=timeout",
        "        )",
        "",
        "        if result.returncode != 0:",
        '            error_msg = result.stderr if result.stderr else "Unknown error"',
        '            return {"error": error_msg, "exit_code": result.returncode}',
        "",
        "        # Try to parse as JSON first",
        "        try:",
        "            return json.loads(result.stdout)",
        "        except json.JSONDecodeError:",
        "            # If not JSON, return as plain output",
        '            return {"output": result.stdout.strip(), "raw": True}',
        "",
        "    except subprocess.TimeoutExpired:",
        f'        return {{"error": f"Timeout - operation took longer than {{timeout}}s", "timeout": timeout}}',
        "    except Exception as e:",
        f'        return {{"error": f"Unexpected error: {{type(e).__name__}} - {{e}}"}}',
        "",
    ]

    return "\n".join(template_lines)

    return template


def generate_mcp_wrapper(skill_name: str) -> str:
    """Generate wrapper for MCP-based tools."""
    base_name = skill_name.replace("-expert", "").replace("_", "-")

    # Common MCP tool patterns
    common_tools = [
        "navigate",
        "screenshot",
        "click",
        "get_text",
        "get_attribute",
        "execute_js",
        "fill_form",
        "scroll",
        "wait_for",
        "get_page_info",
    ]

    template = f"""# === {skill_name.title()} Functions ===
# Auto-generated by generate_monty_wrapper.py

"""

    # Generate function for each common MCP tool
    for tool in common_tools:
        template += generate_mcp_function(base_name, tool)

    return template


def generate_mcp_function(base_name: str, tool_name: str) -> str:
    """Generate a single MCP function wrapper."""
    func_name = f"{base_name}_{tool_name}"

    # Generate function signature and docstring
    signature, docstring = generate_function_signature(base_name, tool_name)

    wrapper = f'''
@register_external_function("{func_name}")
def {signature}:
    """
    {docstring}
    """
    from pathlib import Path
    import subprocess
    import sys
    import json
    
    tool_dir = Path(__file__).parent.parent.parent / "{base_name}-expert" / "tool"
    mcp_server_path = tool_dir / "mcp_server.py"
    
    if not mcp_server_path.exists():
        return {{"error": f"MCP server not found at {{mcp_server_path}}"}}
    
    # Import MCP client
    sys.path.insert(0, str(Path(__file__).parent.parent.parent))
    
    try:
        from mcp_client import MCPClient
        
        # Create MCP client
        client = MCPClient(
            server_path=str(mcp_server_path),
            server_name="{base_name}-mcp",
            is_external=False
        )
        
        # Call to tool
        # Note: This is a simplified wrapper.
        result = client.call_tool_sync("{tool_name}")
        
        return {{"result": result}}
    
    except Exception as e:
        return {{"error": f"MCP call failed: {{e}}"}}
'''

    return wrapper


def generate_function_signature(base_name: str, tool_name: str) -> str:
    """Generate function signature and docstring."""
    # Map tool names to parameters
    tool_params = {
        "navigate": "(url: str, wait_until: str = 'load')",
        "screenshot": "(path: str, full_page: bool = False)",
        "click": "(selector: str)",
        "get_text": "(selector: str) -> str",
        "get_attribute": "(selector: str, attribute: str) -> str",
        "execute_js": "(code: str) -> Any",
        "fill_form": "(selector: str, value: str)",
        "scroll": "(pixels: int = 0)",
        "wait_for": "(selector: str, timeout: int = 5000)",
        "get_page_info": "() -> dict",
    }

    # Generate docstrings
    docstrings = {
        "navigate": "Navigate browser to specified URL.",
        "screenshot": "Take screenshot of current page or element.",
        "click": "Click element by CSS selector.",
        "get_text": "Extract text content from element.",
        "get_attribute": "Get HTML attribute value from element.",
        "execute_js": "Execute JavaScript code in page context.",
        "fill_form": "Fill input field with value.",
        "scroll": "Scroll page by pixels.",
        "wait_for": "Wait for element to appear.",
        "get_page_info": "Get current page information (URL, title, etc.)",
    }

    signature = f"{base_name}_{tool_name}{tool_params.get(tool_name, '')}"
    docstring = docstrings.get(tool_name, "No description available.")

    return signature, docstring


def main():
    if len(sys.argv) < 2:
        print(
            "Usage: python generate_monty_wrapper.py <skill-name> [--mcp] [--output <file>]"
        )
        print("")
        print("Examples:")
        print("  python generate_monty_wrapper.py news-aggregator-expert")
        print("  python generate_monty_wrapper.py playwright-expert --mcp")
        print(
            "  python generate_monty_wrapper.py pdf-downloader-expert --output pdf_functions.py"
        )
        sys.exit(1)

    skill_name = sys.argv[1]

    is_mcp = "--mcp" in sys.argv
    output_file = None

    for i, arg in enumerate(sys.argv):
        if arg == "--output" and i + 1 < len(sys.argv):
            output_file = sys.argv[i + 1]

    # Detect tool type
    if not is_mcp:
        tool_type = detect_tool_type(skill_name)
        is_mcp = tool_type == "mcp"

    # Generate wrapper
    print(f"[+] Generating wrapper for {skill_name}...")
    print(f"    Type: {'MCP' if is_mcp else 'Subprocess'}")

    if is_mcp:
        wrapper_code = generate_mcp_wrapper(skill_name)
    else:
        wrapper_code = generate_subprocess_wrapper(skill_name)

    # Output result
    if output_file:
        with open(output_file, "w", encoding="utf-8") as f:
            f.write(wrapper_code)
        print(f"[OK] Wrapper saved to: {output_file}")
    else:
        print(wrapper_code)


if __name__ == "__main__":
    main()
